project:
  type: website

website:
  title: "_brand.yml Demo"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "RevealJS"
        href: index-revealjs.html
      - text: "Dashboard"
        href: index-dashboard.html
      - text: "Typst"
        href: index-typst.pdf
    tools:
      - icon: github
        href: https://github.com/stanford-brand-yml/quarto-branded-website

format:
  html:
    toc: true

# Use the brand file for all documents in the project
brand: _brand.yml
